### PR TITLE
Feature/bootstrap nav

### PR DESCRIPTION
**Pull request by danieldekerlegand**
This branch adds Bootstrap via a CDN (we can always add it as a gem later). It also adds a simple navigation layout and renders it in the index.

### CODE REVIEW

**Comment by mikevo** [comment]
You need to include the Bootstrap JS code. As of now the mobile view of nav will not work.

**Comment by mikevo** [comment]
jquery is still missing and place it right before </body> instead of the <head> section

    
    
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

**Comment by danieldekerlegand** [comment]
It looks like jQuery is included by default in Rails (at least it's showing up in my sources when I run the app). I moved bootstrap.js to the end of <body> though.

**Comment by mikevo** [comment]
Maybe it's the wrong version because the drop-down (mobile view) does not work when i test it.

**Comment by danieldekerlegand** [comment]
Weird, the toggle is working for me locally. I'll take a look after class.

**Comment by mikevo** [comment]
line 23 should be:
`<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">`

and line 31 should be:
`<div id="navbar" class="navbar-collapse collapse">`

than it works at my notebook.

OT: Does anyone knows if I can push to that PR as it is from a different repo?

**Comment by mikevo** [comment]
I am just playing with the review feature of github

**Review by mikevo — COMMENTED** [review]
Should be fine

**Pull request merged**
