### PR TITLE
Add authentication

### LINKED ISSUE #20: Add authentication
Maybe by using https://www.sitepoint.com/magical-authentication-sorcery/

### PR DESCRIPTION
**Pull request by mikevo**
Closes #20 

Includes stuff from https://www.sitepoint.com/magical-authentication-sorcery/ with modifications and not to the full extend. Only major functionality used.

### CODE REVIEW

**Comment by mikevo** [comment]
Does anyone knows how to authenticate in a test?

**Comment by mikevo** [comment]
i thinks it's cause of this bug https://github.com/NoamB/sorcery/issues/775

**Comment by mikevo** [comment]
i think we should check if sorcery works with the test data generator gem proposed by @kmaus before mergin this pr

**Comment by danieldekerlegand** [comment]
The issue was that the test was now returning a 302 (redirect to the user's page) rather than a 200, so I changed the test case to reflect that and added a comment for clarity.

**Pull request merged**
