### PR TITLE
Fix windows dev issue

### PR DESCRIPTION
**Pull request by mikevo**
Please can someone with access to a windows machine check if this fix is sufficient?

### CODE REVIEW

**Comment by mikevo** [comment]
Do we need this changes? Otherwise we can close this PR and delete the branch.

**Comment by ntalen** [comment]
Sorry for the late comment here: this does indeed work

**Comment by mikevo** [comment]
OK nice but the question is do we need this in the master branch? If yes then we need to merge this PR and not just close it. Otherwise it's fine.

**Comment by ntalen** [comment]
My bad; yeah it should be merged, as long as it's not interrupting anyone else

**Comment by mikevo** [comment]
@ntalen In this case please add a review and merge it afterwards.

**Review by ntalen — APPROVED** [review]
It's good!

**Comment by ntalen** [comment]
Pretty new to Github, thought only the master could do merges.  Learn something new each day~

**Pull request merged**
