### PR TITLE
Draw diagrams

### LINKED ISSUE #40: Create use case model
Use Case Model
* Use Cases
* Use Case Diagram

### PR DESCRIPTION
**Pull request by ntalen**
need some opinions on use-case diagram + docs, in case I missed things or misunderstood anything

closes #40

### CODE REVIEW

**Comment by kmaus** [comment]
Admins should have the ability to manage(change user role, delete, etc) users and manage courses(create and delete).
Teachers should have the ability to manage(create/delete/edit) quizzes.

**Review by kmaus — CHANGES_REQUESTED** [review]
Admins should have the ability to manage(change user role, delete, etc) users and manage courses(create and delete).
Teachers should have the ability to manage(create/delete/edit) quizzes.
Everyone should have the ability to have view and edit their profile.

**Comment by kmaus** [comment]
We currently Quiz everywhere in place of Exam or test, we should stick to that verb-age. It is unclear what `id[pk]` is.

**Review by kmaus — APPROVED** [review]

**Comment by kmaus** [comment]
Odd that it said that the branch was out of date with master when no files were changed by the merge ¯\_(ツ)_/¯

**Comment by mikevo** [comment]
Is it ready to merge?

**Comment by kmaus** [comment]
yep, I was waiting for the checks to pass and got distracted.

**Pull request merged**
